project:
  type: book

book:
  title: "Causal Concepts for Pharmacometricians"
  author: "Francois Mercier and Jim Rogers"
  date: "2/26/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - Chapter1/dags.Rmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



