project:
  type: book

book:
  title: "Causal Concepts for Pharmacometricians"
  author: 
    - Francois Mercier 
    - Jim Rogers
  date: "6/20/2026"
  chapters:
    - index.qmd
    - Chapter0/intro.qmd
    - Chapter1/dags.qmd
    - Chapter2/estimands.qmd
    - references.qmd

format:
  html:
    toc: true
    toc-depth: 4
    theme:
      - cosmo
      - brand
#  pdf:
#    documentclass: scrreprt

bibliography: references.bib





